/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        'primary':                   '#bfc2ff',
        'primary-fixed':             '#e0e0ff',
        'surface-bright':            '#373752',
        'surface-dim':               '#111129',
        'secondary-fixed':           '#e4e4cc',
        'on-secondary-container':    '#b9baa3',
        'secondary-container':       '#494a38',
        'secondary':                 '#c8c8b0',
        'surface-container':         '#1d1d36',
        'on-primary-container':      '#bcbfff',
        'inverse-surface':           '#e2dfff',
        'primary-fixed-dim':         '#bfc2ff',
        'on-background':             '#e2dfff',
        'tertiary':                  '#e9c400',
        'inverse-on-surface':        '#2e2e48',
        'surface-container-high':    '#272741',
        'surface-container-lowest':  '#0b0b24',
        'surface-tint':              '#bfc2ff',
        'surface-variant':           '#32324d',
        'surface':                   '#111129',
        'on-primary':                '#0400ac',
        'tertiary-container':        '#c9a900',
        'on-surface':                '#e2dfff',
        'on-tertiary':               '#3a3000',
        'error':                     '#ffb4ab',
        'surface-container-highest': '#32324d',
        'tertiary-fixed':            '#ffe16d',
        'outline':                   '#8f8fa4',
        'outline-variant':           '#454557',
        'on-secondary':              '#303221',
        'on-tertiary-container':     '#4c3e00',
        'tertiary-fixed-dim':        '#e9c400',
        'secondary-fixed-dim':       '#c8c8b0',
        'background':                '#111129',
        'surface-container-low':     '#191932',
        'on-surface-variant':        '#c5c4db',
        'inverse-primary':           '#363cff',
        'primary-container':         '#1a1aff',
        'error-container':           '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      spacing: {
        base:             '8px',
        gutter:           '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-md':     ['Work Sans',     'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'label-bold':  ['Anybody',       'sans-serif'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-bold':  ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}